OPENAI_API_KEY = "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"

[connections.snowpark]
user = "SHAWNMAI"
password = "Nekgef-dijdum-3jekte"
warehouse = "COMPUTE_WH"
role = "ACCOUNTADMIN"
account = "EWQBGGY-UK00228"


db_username = "Jane"
db_password = "12345qwerty"

[my_cool_secrets]
things_i_like = ["Streamlit", "Python"]