OPENAI_API_KEY = "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"

[connections.snowpark]
user = "SHAWNMAI"
password = "Nekgef-dijdum-3jekte"
warehouse = "COMPUTE_WH"
role = "ACCOUNTADMIN"
account = "EWQBGGY-UK00228"
database = "BIGSUPPLYCO"
schema = "BIGSUPPLYCO"
